[project]
name = "rvc-webgui-fork"
version = "0.1.0"
description = "A Fork of RVC WebGUI with many quality of life improvements"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "absl-py>=1.2.0",
    "aria2>=0.0.1b0",
    "audioread>=3.0.1",
    "av>=14.4.0",
    "colorama>=0.4.5",
    "cython>=3.1.1",
    "fairseq",
    "faiss-cpu>=1.7.3",
    "ffmpeg-python>=0.2.0",
    "ffmpy>=0.3.1",
    "fsspec>=2022.11.0",
    "gitpython>=3.1.44",
    "gradio>=3.34.0",
    "httpx>=0.28.1",
    "jinja2>=3.1.2",
    "joblib>=1.1.0",
    "json5>=0.12.0",
    "jurigged>=0.6.1",
    "librosa>=0.11.0",
    "matplotlib>=3.7.0",
    "matplotlib-inline>=0.1.3",
    "numba>=0.56.4",
    "numpy>=1.23.5",
    "onnxruntime-gpu>=1.22.0 ; sys_platform != 'darwin'",
    "pillow>=9.1.1",
    "poluvr[gpu]>=1.9.0",
    "praat-parselmouth>=0.4.2",
    "pyasn1>=0.4.8",
    "pyasn1-modules>=0.2.8",
    "pydub>=0.25.1",
    "pygobject>=3.52.3",
    "pygobject-stubs>=2.13.0",
    "python-dotenv>=1.0.0",
    "pyworld>=0.3.5",
    "pyyaml>=6.0",
    "resampy>=0.4.2",
    "scikit-learn>=1.6.1",
    "scipy>=1.15.3",
    "sounddevice>=0.5.2",
    "soundfile>=0.12.1",
    "sympy>=1.11.1",
    "tabulate>=0.8.10",
    "tensorboard>=2.19.0",
    "tensorboardx>=2.6.2.2",
    "torch>=2.7.0",
    "torchaudio>=2.7.0",
    "torchcrepe>=0.0.24",
    "torchfcpe>=0.0.4",
    "torchvision>=0.22.0",
    "tornado>=6.1",
    "tqdm>=4.63.1",
    "uc-micro-py>=1.0.1",
    "uvicorn>=0.21.1",
    "werkzeug>=2.2.3",
]

[tool.uv.sources]
fairseq = { git = "https://github.com/liyaodev/fairseq.git" }
