name: Build and Push Docker Image

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract Git commit SHA
        id: vars
        run: echo "sha_short=${GITHUB_SHA::7}" >> $GITHUB_OUTPUT

      - name: Check Disk Space
        run: | 
          set xe
          df -H
      # From here https://gist.github.com/antiphishfish/1e3fbc3f64ef6f1ab2f47457d2da5d9d
      - name: Free Disk Space 
        run: |
          set -xe
          mkdir empty_dir
          sudo rsync -a --delete empty_dir/ /usr/share/dotnet
          sudo rsync -a --delete empty_dir/ /usr/share/swift
          sudo rsync -a --delete empty_dir/ /usr/local/lib/android
          sudo rsync -a --delete empty_dir/ /opt/ghc
          sudo rsync -a --delete empty_dir/ /usr/local/.ghcup
          sudo rsync -a --delete empty_dir/ /usr/local/share/boost
          sudo rsync -a --delete empty_dir/ "$AGENT_TOOLSDIRECTORY"
          sudo rsync -a --delete empty_dir/ /opt/hostedtoolcache/
          sudo rsync -a --delete empty_dir/ /usr/local/graalvm/
          sudo rsync -a --delete empty_dir/ /usr/local/share/powershell
          sudo rsync -a --delete empty_dir/ /usr/local/share/chromium
          sudo rsync -a --delete empty_dir/ /usr/local/lib/node_modules
          rm -rf empty_dir
          
      - name: After Cleanup
        run: |
          set -xe
          df -H

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: |
            ghcr.io/${{ github.repository }}:${{ steps.vars.outputs.sha_short }}
            ghcr.io/${{ github.repository }}:latest
          labels: |
            org.opencontainers.image.title=RVC WebGUI Fork
            org.opencontainers.image.description=A fork of RVC Web GUI for voice conversion, with additional features and improvements.
            org.opencontainers.image.version=${{ steps.vars.outputs.sha_short }}
            org.opencontainers.image.url=https://github.com/${{ github.repository }}
            org.opencontainers.image.source=https://github.com/${{ github.repository }}
            org.opencontainers.image.revision=${{ github.sha }}
            org.opencontainers.image.created=${{ github.event.head_commit.timestamp }}
            org.opencontainers.image.licenses=MIT
            maintainer=yamada-sexta

          cache-from: type=gha
          cache-to: type=gha,mode=max
